GalaxHubWhitelist = {
    "WhyMayko",
    "sakumoriya",
    "Nullxietys_World",
    "XOFsleeperagent",
    "lambpelt",
    "tfuegoodly",
    "germanbadguy20",
    "Anti_Krip",
    "LYM1H",
    "goodgoods77",
    "woogadodobo",
    "thehonoredih",
    "EllaPhoenixToxic37",
    "junkbot6004",
    "thai1237",
    "gaxl",
    "Slebv2",
    "edenurheart",
    "probablyzephyr",
    "fbup",
    "coolestpersonever99",
    "dtbsinfuls",
    "adamgti",
    "7seesons",
    "DogSeamanAddict",
    "kooiikc",
    "SeRh1O_Main",
    "419victory",
    "NEUTRALlSATION",

    -- Add more users below this line!
}
